In [1]:
!pip install numpy
print("numpy installed")

numpy installed


In [2]:
import numpy as np
print("imported")

imported


In [3]:
temp = [32.4,45.2,18.2,34.4,23.4,17.5,30.3]
temperature = np.array(temp)
avg = np.mean(temperature)
print(avg)

28.771428571428572


In [4]:
#matrix
matrix = np.array([[2,4,6],[8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
# with default values
zeros_array = np.zeros(3)
print(zeros_array)

[0. 0. 0.]


In [6]:
#ones function
ones_func = np.ones((2,2))
print(ones_func)

[[1. 1.]
 [1. 1.]]


In [7]:
#full function 
# np.full(shape,number)
full_func = np.full((2,2),7)
print(full_func)

[[7 7]
 [7 7]]


In [8]:
# creating sequences of numbers in numpy
#arange(start,stop,step)
arr = np.arange(1,3,1)
print(arr)

[1 2]


In [9]:
#identity matrix
#np.eye(shape)
iden = np.eye(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
